import { AnalysisReport } from '../services/api';

/**
 * Downloads a structured text/markdown report for the analyzed resume
 */
export function downloadAnalysisReport(report: AnalysisReport) {
  const dateStr = new Date(report.analyzedAt || Date.now()).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
  });

  const content = `===================================================================
HIRELENS — RESUME AUDIT & ATS INTELLIGENCE REPORT
===================================================================
File: ${report.fileName}
Analyzed: ${dateStr}
Overall Score: ${report.overallScore}/100

-------------------------------------------------------------------
1. EXECUTIVE SCORE BREAKDOWN
-------------------------------------------------------------------
- Overall Score:           ${report.overallScore}/100
- ATS Compatibility:       ${report.atsScore}%
- Content Quality:         ${report.contentScore}%
- Skills & Tech Stack:     ${report.skillsScore}%
- Recruiter Screen:        ${report.recruiterScore}%
${report.jobDescription ? `- Targeted Job Match:     ${report.jobMatchScore}%\n` : ''}
Scoring Methodology:
Overall = (ATS × 30%) + (Content × 25%) + (Skills × 20%) + (Recruiter × 25%)

-------------------------------------------------------------------
2. ATS ESSENTIALS & PARSEABILITY (${report.categories.ats.passedChecks}/${report.categories.ats.totalChecks} PASSED)
-------------------------------------------------------------------
${report.categories.ats.items.map(item => `[${item.passed ? 'PASS' : 'WARN'}] ${item.name}: ${item.detail}`).join('\n')}

-------------------------------------------------------------------
3. RESUME STRUCTURE AUDIT
-------------------------------------------------------------------
${report.categories.structure.items.map(sec => `[${sec.status.toUpperCase()}] ${sec.name}: ${sec.detail}`).join('\n')}

-------------------------------------------------------------------
4. CONTENT QUALITY & ACHIEVEMENTS
-------------------------------------------------------------------
- Quantifiable Metrics Identified: ${report.categories.content.quantifiedAchievementsCount}
${report.categories.content.weakBullets.length > 0 ? `
Weak Statements Needing Improvement (${report.categories.content.weakBullets.length}):
${report.categories.content.weakBullets.map((b, i) => `
#${i + 1} Original: "${b.original}"
   Issue:    ${b.reason}
   Suggested: "${b.suggestion}"
`).join('\n')}` : '\nNo weak or duty-only statements detected. Excellent achievement phrasing!'}

-------------------------------------------------------------------
5. DETECTED SKILLS & DOMAIN STRENGTH
-------------------------------------------------------------------
Extracted Skills (${report.categories.skills.detectedSkills.length}):
${report.categories.skills.detectedSkills.join(', ')}

Domain Evaluation:
${report.categories.skills.skillStrength.map(s => `- ${s.category}: ${s.level}`).join('\n')}

-------------------------------------------------------------------
6. KEYWORD ALIGNMENT
-------------------------------------------------------------------
- Matched Keywords: ${report.categories.keywords.matchedKeywords.join(', ') || 'None'}
- Missing Keywords: ${report.categories.keywords.missingKeywords.join(', ') || 'None'}

-------------------------------------------------------------------
7. RECRUITER HUMAN SCREEN
-------------------------------------------------------------------
Key Strengths:
${report.categories.recruiter.strengths.map(s => `✓ ${s}`).join('\n')}

Areas for Improvement:
${report.categories.recruiter.improvements.map(i => `! ${i}`).join('\n')}

-------------------------------------------------------------------
8. HIGH-PRIORITY ACTION PLAN
-------------------------------------------------------------------
${report.actionPlan.map((plan, idx) => `
${idx + 1}. [${plan.priority}] ${plan.title}
   Why:    ${plan.reason}
   Action: ${plan.action}
   Sample: ${plan.suggestionSample}
`).join('\n')}

===================================================================
Generated by HireLens Resume Intelligence
https://hirelens.ai
===================================================================
`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `HireLens_Audit_${report.fileName.replace(/\.[^/.]+$/, '')}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
